[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
bitvec = "1.0.1"
cargo-aoc = "0.3.8"
find_all = "2.0.0"
itertools = "0.13.0"
pathfinding = "4.14.0"
regex = "1.11.1"
scanf = "1.2.1"
